leftnav:
- identifier: b78eb105-91e5-a2a5-99b8-4ca60f4122d6
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: external-fcaee75f096243e7b37900b4d7ee7c04
  name: Quantum Information Science I, Part 1
  url: https://openlearninglibrary.mit.edu/courses/course-v1:MITx+8.370.1x+1T2018/about
  weight: 1000
- identifier: external-6de7f2ce86b545b3ba92714fe85a3431
  name: Quantum Information Science I, Part 2
  url: https://openlearninglibrary.mit.edu/courses/course-v1:MITx+8.370.2x+1T2018/about
  weight: 1010
- identifier: external-df9563af06f04c19a72551ae143bcadb
  name: Quantum Information Science I, Part 3
  url: https://openlearninglibrary.mit.edu/courses/course-v1:MITx+8.370.3x+1T2018/about
  weight: 1020
